### ISSUE TITLE
Plugin won't load

### ISSUE THREAD

**Issue by 1sasafras1** [Firebreath15/iControlU#10]
This might be because of spigot but this is the console output:
`[11:57:23] [Server thread/INFO]: Set PluginClassLoader as parallel capable
[11:57:23] [Server thread/ERROR]: Could not load 'plugins/iControlU.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: LibsDisguises
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:219) [spigot-1.8.7-20150608a.jar:git-Spigot-07a5b1b-53433de]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:291) [spigot-1.8.7-20150608a.jar:git-Spigot-07a5b1b-53433de]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [spigot-1.8.7-20150608a.jar:git-Spigot-07a5b1b-53433de]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:528) [spigot-1.8.7-20150608a.jar:git-Spigot-07a5b1b-53433de]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_65]
[11:57:23] [Server thread/ERROR]: ebean.properties not found
[11:57:24] [Server thread/INFO]: DataSourcePool [Gringotts] autoCommit[false] transIsolation[SERIALIZABLE] min[2] max[20]
[11:57:25] [Server thread/INFO]: SubClassFactory parent ClassLoader [org.bukkit.plugin.java.PluginClassLoader]
[11:57:25] [Server thread/INFO]: Entities enhanced[0] subclassed[2]`

**Comment by 1sasafras1** [comment]
Just read the line that says `rg.bukkit.plugin.UnknownDependencyException: LibsDisguises at `
 added the plugin worked

**Comment by Firebreath15** [comment]
Hmm. Make sure that you're using the correct supported versions of ProtocolLib - that should help :)
